### ISSUE TITLE
Convert from scrolling to flipping

### ISSUE THREAD

**Issue by cmurray191** [Fattimo/hear-a-tale-awakening#18]
Have the text for one page along with previous/next buttons rather than scrolling. All chapters must start on a new page.

**Comment by cmurray191** [comment]
Have the text for one page along with previous/next buttons rather than scrolling. All chapters must start on a new page.

**Comment by Fattimo** [comment]
https://stackoverflow.com/questions/3403789/work-out-how-many-characters-can-fit-into-div-with-javascript
